package com.wenbo.webpiao.model;

public class Station {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.id
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.simple_code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    private String simpleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.zh_code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    private String zhCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.station_code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    private String stationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.pinying_code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    private String pinyingCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.simple_pinying_code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    private String simplePinyingCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.id
     *
     * @return the value of station.id
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.id
     *
     * @param id the value for station.id
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.simple_code
     *
     * @return the value of station.simple_code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public String getSimpleCode() {
        return simpleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.simple_code
     *
     * @param simpleCode the value for station.simple_code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public void setSimpleCode(String simpleCode) {
        this.simpleCode = simpleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.zh_code
     *
     * @return the value of station.zh_code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public String getZhCode() {
        return zhCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.zh_code
     *
     * @param zhCode the value for station.zh_code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public void setZhCode(String zhCode) {
        this.zhCode = zhCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.station_code
     *
     * @return the value of station.station_code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.station_code
     *
     * @param stationCode the value for station.station_code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public void setStationCode(String stationCode) {
        this.stationCode = stationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.pinying_code
     *
     * @return the value of station.pinying_code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public String getPinyingCode() {
        return pinyingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.pinying_code
     *
     * @param pinyingCode the value for station.pinying_code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public void setPinyingCode(String pinyingCode) {
        this.pinyingCode = pinyingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.simple_pinying_code
     *
     * @return the value of station.simple_pinying_code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public String getSimplePinyingCode() {
        return simplePinyingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.simple_pinying_code
     *
     * @param simplePinyingCode the value for station.simple_pinying_code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public void setSimplePinyingCode(String simplePinyingCode) {
        this.simplePinyingCode = simplePinyingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.code
     *
     * @return the value of station.code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.code
     *
     * @param code the value for station.code
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }
}