package com.wenbo.webpiao.model;

import java.util.ArrayList;
import java.util.List;

public class StationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public StationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSimpleCodeIsNull() {
            addCriterion("simple_code is null");
            return (Criteria) this;
        }

        public Criteria andSimpleCodeIsNotNull() {
            addCriterion("simple_code is not null");
            return (Criteria) this;
        }

        public Criteria andSimpleCodeEqualTo(String value) {
            addCriterion("simple_code =", value, "simpleCode");
            return (Criteria) this;
        }

        public Criteria andSimpleCodeNotEqualTo(String value) {
            addCriterion("simple_code <>", value, "simpleCode");
            return (Criteria) this;
        }

        public Criteria andSimpleCodeGreaterThan(String value) {
            addCriterion("simple_code >", value, "simpleCode");
            return (Criteria) this;
        }

        public Criteria andSimpleCodeGreaterThanOrEqualTo(String value) {
            addCriterion("simple_code >=", value, "simpleCode");
            return (Criteria) this;
        }

        public Criteria andSimpleCodeLessThan(String value) {
            addCriterion("simple_code <", value, "simpleCode");
            return (Criteria) this;
        }

        public Criteria andSimpleCodeLessThanOrEqualTo(String value) {
            addCriterion("simple_code <=", value, "simpleCode");
            return (Criteria) this;
        }

        public Criteria andSimpleCodeLike(String value) {
            addCriterion("simple_code like", value, "simpleCode");
            return (Criteria) this;
        }

        public Criteria andSimpleCodeNotLike(String value) {
            addCriterion("simple_code not like", value, "simpleCode");
            return (Criteria) this;
        }

        public Criteria andSimpleCodeIn(List<String> values) {
            addCriterion("simple_code in", values, "simpleCode");
            return (Criteria) this;
        }

        public Criteria andSimpleCodeNotIn(List<String> values) {
            addCriterion("simple_code not in", values, "simpleCode");
            return (Criteria) this;
        }

        public Criteria andSimpleCodeBetween(String value1, String value2) {
            addCriterion("simple_code between", value1, value2, "simpleCode");
            return (Criteria) this;
        }

        public Criteria andSimpleCodeNotBetween(String value1, String value2) {
            addCriterion("simple_code not between", value1, value2, "simpleCode");
            return (Criteria) this;
        }

        public Criteria andZhCodeIsNull() {
            addCriterion("zh_code is null");
            return (Criteria) this;
        }

        public Criteria andZhCodeIsNotNull() {
            addCriterion("zh_code is not null");
            return (Criteria) this;
        }

        public Criteria andZhCodeEqualTo(String value) {
            addCriterion("zh_code =", value, "zhCode");
            return (Criteria) this;
        }

        public Criteria andZhCodeNotEqualTo(String value) {
            addCriterion("zh_code <>", value, "zhCode");
            return (Criteria) this;
        }

        public Criteria andZhCodeGreaterThan(String value) {
            addCriterion("zh_code >", value, "zhCode");
            return (Criteria) this;
        }

        public Criteria andZhCodeGreaterThanOrEqualTo(String value) {
            addCriterion("zh_code >=", value, "zhCode");
            return (Criteria) this;
        }

        public Criteria andZhCodeLessThan(String value) {
            addCriterion("zh_code <", value, "zhCode");
            return (Criteria) this;
        }

        public Criteria andZhCodeLessThanOrEqualTo(String value) {
            addCriterion("zh_code <=", value, "zhCode");
            return (Criteria) this;
        }

        public Criteria andZhCodeLike(String value) {
            addCriterion("zh_code like", value, "zhCode");
            return (Criteria) this;
        }

        public Criteria andZhCodeNotLike(String value) {
            addCriterion("zh_code not like", value, "zhCode");
            return (Criteria) this;
        }

        public Criteria andZhCodeIn(List<String> values) {
            addCriterion("zh_code in", values, "zhCode");
            return (Criteria) this;
        }

        public Criteria andZhCodeNotIn(List<String> values) {
            addCriterion("zh_code not in", values, "zhCode");
            return (Criteria) this;
        }

        public Criteria andZhCodeBetween(String value1, String value2) {
            addCriterion("zh_code between", value1, value2, "zhCode");
            return (Criteria) this;
        }

        public Criteria andZhCodeNotBetween(String value1, String value2) {
            addCriterion("zh_code not between", value1, value2, "zhCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeIsNull() {
            addCriterion("station_code is null");
            return (Criteria) this;
        }

        public Criteria andStationCodeIsNotNull() {
            addCriterion("station_code is not null");
            return (Criteria) this;
        }

        public Criteria andStationCodeEqualTo(String value) {
            addCriterion("station_code =", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeNotEqualTo(String value) {
            addCriterion("station_code <>", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeGreaterThan(String value) {
            addCriterion("station_code >", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("station_code >=", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeLessThan(String value) {
            addCriterion("station_code <", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeLessThanOrEqualTo(String value) {
            addCriterion("station_code <=", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeLike(String value) {
            addCriterion("station_code like", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeNotLike(String value) {
            addCriterion("station_code not like", value, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeIn(List<String> values) {
            addCriterion("station_code in", values, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeNotIn(List<String> values) {
            addCriterion("station_code not in", values, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeBetween(String value1, String value2) {
            addCriterion("station_code between", value1, value2, "stationCode");
            return (Criteria) this;
        }

        public Criteria andStationCodeNotBetween(String value1, String value2) {
            addCriterion("station_code not between", value1, value2, "stationCode");
            return (Criteria) this;
        }

        public Criteria andPinyingCodeIsNull() {
            addCriterion("pinying_code is null");
            return (Criteria) this;
        }

        public Criteria andPinyingCodeIsNotNull() {
            addCriterion("pinying_code is not null");
            return (Criteria) this;
        }

        public Criteria andPinyingCodeEqualTo(String value) {
            addCriterion("pinying_code =", value, "pinyingCode");
            return (Criteria) this;
        }

        public Criteria andPinyingCodeNotEqualTo(String value) {
            addCriterion("pinying_code <>", value, "pinyingCode");
            return (Criteria) this;
        }

        public Criteria andPinyingCodeGreaterThan(String value) {
            addCriterion("pinying_code >", value, "pinyingCode");
            return (Criteria) this;
        }

        public Criteria andPinyingCodeGreaterThanOrEqualTo(String value) {
            addCriterion("pinying_code >=", value, "pinyingCode");
            return (Criteria) this;
        }

        public Criteria andPinyingCodeLessThan(String value) {
            addCriterion("pinying_code <", value, "pinyingCode");
            return (Criteria) this;
        }

        public Criteria andPinyingCodeLessThanOrEqualTo(String value) {
            addCriterion("pinying_code <=", value, "pinyingCode");
            return (Criteria) this;
        }

        public Criteria andPinyingCodeLike(String value) {
            addCriterion("pinying_code like", value, "pinyingCode");
            return (Criteria) this;
        }

        public Criteria andPinyingCodeNotLike(String value) {
            addCriterion("pinying_code not like", value, "pinyingCode");
            return (Criteria) this;
        }

        public Criteria andPinyingCodeIn(List<String> values) {
            addCriterion("pinying_code in", values, "pinyingCode");
            return (Criteria) this;
        }

        public Criteria andPinyingCodeNotIn(List<String> values) {
            addCriterion("pinying_code not in", values, "pinyingCode");
            return (Criteria) this;
        }

        public Criteria andPinyingCodeBetween(String value1, String value2) {
            addCriterion("pinying_code between", value1, value2, "pinyingCode");
            return (Criteria) this;
        }

        public Criteria andPinyingCodeNotBetween(String value1, String value2) {
            addCriterion("pinying_code not between", value1, value2, "pinyingCode");
            return (Criteria) this;
        }

        public Criteria andSimplePinyingCodeIsNull() {
            addCriterion("simple_pinying_code is null");
            return (Criteria) this;
        }

        public Criteria andSimplePinyingCodeIsNotNull() {
            addCriterion("simple_pinying_code is not null");
            return (Criteria) this;
        }

        public Criteria andSimplePinyingCodeEqualTo(String value) {
            addCriterion("simple_pinying_code =", value, "simplePinyingCode");
            return (Criteria) this;
        }

        public Criteria andSimplePinyingCodeNotEqualTo(String value) {
            addCriterion("simple_pinying_code <>", value, "simplePinyingCode");
            return (Criteria) this;
        }

        public Criteria andSimplePinyingCodeGreaterThan(String value) {
            addCriterion("simple_pinying_code >", value, "simplePinyingCode");
            return (Criteria) this;
        }

        public Criteria andSimplePinyingCodeGreaterThanOrEqualTo(String value) {
            addCriterion("simple_pinying_code >=", value, "simplePinyingCode");
            return (Criteria) this;
        }

        public Criteria andSimplePinyingCodeLessThan(String value) {
            addCriterion("simple_pinying_code <", value, "simplePinyingCode");
            return (Criteria) this;
        }

        public Criteria andSimplePinyingCodeLessThanOrEqualTo(String value) {
            addCriterion("simple_pinying_code <=", value, "simplePinyingCode");
            return (Criteria) this;
        }

        public Criteria andSimplePinyingCodeLike(String value) {
            addCriterion("simple_pinying_code like", value, "simplePinyingCode");
            return (Criteria) this;
        }

        public Criteria andSimplePinyingCodeNotLike(String value) {
            addCriterion("simple_pinying_code not like", value, "simplePinyingCode");
            return (Criteria) this;
        }

        public Criteria andSimplePinyingCodeIn(List<String> values) {
            addCriterion("simple_pinying_code in", values, "simplePinyingCode");
            return (Criteria) this;
        }

        public Criteria andSimplePinyingCodeNotIn(List<String> values) {
            addCriterion("simple_pinying_code not in", values, "simplePinyingCode");
            return (Criteria) this;
        }

        public Criteria andSimplePinyingCodeBetween(String value1, String value2) {
            addCriterion("simple_pinying_code between", value1, value2, "simplePinyingCode");
            return (Criteria) this;
        }

        public Criteria andSimplePinyingCodeNotBetween(String value1, String value2) {
            addCriterion("simple_pinying_code not between", value1, value2, "simplePinyingCode");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table station
     *
     * @mbggenerated do_not_delete_during_merge Sat Dec 28 18:47:43 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table station
     *
     * @mbggenerated Sat Dec 28 18:47:43 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}